import json
import pandas as pd
from datetime import date

from common import CLUSTERS_FILE, ROOT_DIR


# ============================================================
# CONFIGURATION
# ============================================================
#
# Builds docs/players.js for the player builder game in
# docs/index.html. GitHub Pages serves the docs/ folder.
#
# The data is written as a JS file (not JSON) so the page
# also works when index.html is opened straight from disk.

PLAYERS_INPUT = ROOT_DIR / "player_adjusted.csv"
SITE_OUTPUT = ROOT_DIR / "docs" / "players.js"

ATTRIBUTES = [
    "Firepower",
    "Entrying",
    "Trading",
    "Opening",
    "Clutching",
    "Sniping",
    "Utility"
]

# Teams need this many active players to be rolled,
# so there is a real choice of player
MIN_PLAYERS_PER_TEAM = 3

# Only teams from the strongest clusters can be rolled
MAX_CLUSTER = 4

# Adjusted attributes can go past 100, so they are capped
ATTRIBUTE_CEILING = 100

# Sniping splits into two groups: AWPers (~85-100) and
# riflers (~0). Players at or above this raw Sniping value
# count as AWPers.
AWPER_THRESHOLD = 40


# ============================================================
# LOAD PLAYERS
# ============================================================

players = pd.read_csv(PLAYERS_INPUT)

clusters = pd.read_csv(CLUSTERS_FILE)
cluster_lookup = dict(zip(clusters["team"], clusters["cluster"]))

players["cluster"] = players["team"].map(cluster_lookup)

players = players[
    (players["status"] == "active") &
    (players["cluster"] <= MAX_CLUSTER)
].dropna(subset=[f"{a} adjusted" for a in ATTRIBUTES])

team_sizes = players.groupby("team").size()
players = players[
    players["team"].isin(
        team_sizes[team_sizes >= MIN_PLAYERS_PER_TEAM].index
    )
]


# ============================================================
# NORMALIZE SNIPING
# ============================================================
#
# Raw Sniping mostly says whether a player is an AWPer, not
# how good they are. AWPers are rescaled to 0-100 by their
# rank among the game's AWPers (best = 100, median ~ 50),
# the same spread as the other attributes. Riflers get 0.

players["Sniping adjusted"] = players["Sniping adjusted"].astype(float)

awpers = players["Sniping"] >= AWPER_THRESHOLD

awper_rank = players.loc[awpers, "Sniping adjusted"].rank(method="average")

players.loc[awpers, "Sniping adjusted"] = (
    100 * (awper_rank - 1) / (awpers.sum() - 1)
)

players.loc[~awpers, "Sniping adjusted"] = 0


# ============================================================
# BUILD TEAMS
# ============================================================

teams = []

for team_name, group in players.groupby("team"):

    teams.append({
        "name": team_name,
        "cluster": int(group["cluster"].iloc[0]),
        "multiplier": round(float(group["multiplier"].iloc[0]), 3),
        "players": [
            {
                "name": row["playername"],
                "age": None if pd.isna(row["age"]) else int(row["age"]),
                "stats": {
                    a: round(min(float(row[f"{a} adjusted"]), ATTRIBUTE_CEILING), 1)
                    for a in ATTRIBUTES
                },
                "raw": {
                    a: int(row[a])
                    for a in ATTRIBUTES
                }
            }
            for _, row in group.sort_values("playername").iterrows()
        ]
    })


# ============================================================
# SAVE
# ============================================================

data = {
    "generated": date.today().isoformat(),
    "attributes": ATTRIBUTES,
    "teams": teams
}

SITE_OUTPUT.parent.mkdir(exist_ok=True)

SITE_OUTPUT.write_text(
    "// Generated by scripts/build_site.py from player_adjusted.csv\n"
    f"window.GAME_DATA = {json.dumps(data, ensure_ascii=False)};\n",
    encoding="utf-8"
)

print(f"Teams:   {len(teams)}")
print(f"AWPers:  {awpers.sum()}")
print(f"Players: {sum(len(t['players']) for t in teams)}")
print(f"Saved to {SITE_OUTPUT.relative_to(ROOT_DIR)}")
